runtime: python37

instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /manifest\.json
  static_files: frontend/build/manifest.json
  upload: frontend/build/manifest\.json

- url: /static
  static_dir: frontend/build/static

- url: /scripts
  static_dir: scripts

- url: .*
  script: auto

